
let currentPhoto=null,photoAction='none',scannerActive=false,editingToolId=null;
document.addEventListener('DOMContentLoaded',()=>{
    generateBarcodeId();
    loadTools();
    loadStats();
    loadLocations();
    loadAuditLog();
    document.getElementById('manualBarcode').addEventListener('keypress',e=>{if(e.key==='Enter')manualScan()});
    document.getElementById('toolModal').addEventListener('click',e=>{if(e.target===e.currentTarget)closeModal()});
    document.querySelectorAll('.tab').forEach(tab=>tab.addEventListener('click',()=>switchTab(tab.getAttribute('data-tab')||tab.textContent.toLowerCase())));
});
async function apiGet(endpoint,params={}){const q=new URLSearchParams(params).toString();const url=q?`${endpoint}?${q}`:endpoint;const r=await fetch(url);return r.json()}
async function apiPost(endpoint,data){const r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});return r.json()}
async function apiDelete(endpoint){const r=await fetch(endpoint,{method:'DELETE'});return r.json()}
function switchTab(tabName){
    const tabs = document.querySelectorAll('.tab');
    const panels = document.querySelectorAll('.panel');
    tabs.forEach(t=>t.classList.remove('active'));
    panels.forEach(p=>p.classList.remove('active'));
    const mapping = {add:0,inventory:1,scan:2,labels:3,audit:4};
    const tabIndex = mapping[tabName];
    if(tabIndex!==undefined && tabs[tabIndex]) tabs[tabIndex].classList.add('active');
    const panel = document.getElementById('panel-'+tabName);
    if(panel) panel.classList.add('active');
    if(tabName==='inventory'){loadTools();loadStats()}
    if(tabName==='labels')updateLabelList();
    if(tabName==='audit')loadAuditLog();
}
function generateBarcodeId(){const p="TL",ts=Date.now().toString(36).toUpperCase().slice(-8),rand=Math.random().toString(36).substring(2,6).toUpperCase();const id=p+ts+rand;document.getElementById('barcodeId').value=id;generateBarcodePreview(id);return id}
function regenerateBarcode(){generateBarcodeId();showToast('New barcode ID generated')}
function generateBarcodePreview(code){const c=document.getElementById('previewBarcodeContainer'),s=document.getElementById('previewBarcode');if(code&&typeof JsBarcode!=='undefined'){c.style.display='block';JsBarcode(s,code,{format:"CODE128",lineColor:"#000",width:2,height:60,displayValue:true,fontSize:14,margin:10})}}
function handlePhotoSelect(e){const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=e=>{const img=new Image();img.onload=()=>{const cv=document.createElement('canvas'),ctx=cv.getContext('2d');let w=img.width,h=img.height;const mx=800;if(w>mx){h=(h*mx)/w;w=mx}cv.width=w;cv.height=h;ctx.drawImage(img,0,0,w,h);currentPhoto=cv.toDataURL('image/jpeg',0.7);photoAction='new';document.getElementById('photoPreview').src=currentPhoto;document.getElementById('photoUpload').classList.add('has-image');document.getElementById('clearPhotoBtn').style.display='inline-block'};img.src=e.target.result};r.readAsDataURL(f)}
function clearPhoto(){currentPhoto=null;photoAction=editingToolId?'remove':'none';document.getElementById('photoInput').value='';document.getElementById('photoPreview').src='';document.getElementById('photoUpload').classList.remove('has-image');document.getElementById('clearPhotoBtn').style.display='none'}
async function addTool(e){e.preventDefault();const data={barcode:document.getElementById('barcodeId').value,title:document.getElementById('toolTitle').value,price:parseFloat(document.getElementById('toolPrice').value||0),description:document.getElementById('toolDesc').value,condition:document.getElementById('toolCondition').value,shelf:document.getElementById('toolShelf').value,row_num:document.getElementById('toolRow').value,bin:document.getElementById('toolBin').value,notes:document.getElementById('toolNotes').value,photo_base64:photoAction==='keep'?'KEEP_EXISTING':photoAction==='remove'?'REMOVE':currentPhoto};let res;if(editingToolId){res=await apiPost('/api/tools/'+editingToolId,data);showToast('Tool updated!');editingToolId=null;document.querySelector('#panel-add .card-title').textContent='➕ Add New Tool';document.querySelector('button[type="submit"]').textContent='💾 Save Tool & Generate Barcode'}else{res=await apiPost('/api/tools',data);showToast('✅ "'+data.title+'" added!')}resetForm();generateBarcodeId();loadLocations();setTimeout(()=>switchTab('inventory'),500)}
function resetForm(){document.getElementById('addToolForm').reset();clearPhoto();editingToolId=null;photoAction='none';document.querySelector('#panel-add .card-title').textContent='➕ Add New Tool';document.querySelector('button[type="submit"]').textContent='💾 Save Tool & Generate Barcode'}
async function loadTools(){const params={search:document.getElementById('searchInput').value,status:document.getElementById('statusFilter').value,sort:document.getElementById('sortFilter').value,shelf:document.getElementById('shelfFilter').value,row:document.getElementById('rowFilter').value,bin:document.getElementById('binFilter').value};const d=await apiGet('/api/tools',params);renderTools(d.tools)}
function renderTools(tools){const c=document.getElementById('inventoryList');if(tools.length===0){c.innerHTML='<div class="empty-state"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" width="80" height="80"><circle cx="11" cy="11" r="8"/><line x1="21" y1="21" x2="16.65" y2="16.65"/></svg><h3>No tools found</h3><p>Try adjusting search or filters.</p></div>';return}c.innerHTML=tools.map(t=>`<div class="tool-card ${t.status}"><div class="tool-image">${t.photo_url?`<img src="${t.photo_url}" alt="${t.title}">`:`<svg width="40" height="40" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><rect x="3" y="3" width="18" height="18" rx="2"/><circle cx="8.5" cy="8.5" r="1.5"/><polyline points="21 15 16 10 5 21"/></svg>`}${t.shelf||t.row_num||t.bin?`<div class="tool-location-badge">${[t.shelf,t.row_num,t.bin].filter(Boolean).join('-')}</div>`:''}</div><div class="tool-info"><div style="display:flex;justify-content:space-between;align-items:start;margin-bottom:6px"><div class="tool-title">${t.title}</div><span class="status-badge ${t.status}">${t.status}</span></div><div class="tool-desc">${t.description||'No description'}</div><div class="tool-meta"><span>${t.condition}</span>${t.shelf?`<span>Shelf ${t.shelf}</span>`:''}${t.row_num?`<span>Row ${t.row_num}</span>`:''}${t.bin?`<span>Bin ${t.bin}</span>`:''}</div><div class="tool-price">$${parseFloat(t.price).toFixed(2)}</div><div class="tool-actions"><button class="btn btn-sm btn-secondary" onclick="viewTool(${t.id})">👁️ View</button><button class="btn btn-sm btn-secondary" onclick="editTool(${t.id})">✏️ Edit</button>${t.status==='available'?`<button class="btn btn-sm btn-success" onclick="sellTool(${t.id})">💰 Sell</button>`:''}<button class="btn btn-sm btn-danger" onclick="deleteTool(${t.id})">🗑️</button></div></div></div>`).join('')}
function searchTools(){loadTools()}
function clearFilters(){document.getElementById('searchInput').value='';document.getElementById('statusFilter').value='';document.getElementById('shelfFilter').value='';document.getElementById('rowFilter').value='';document.getElementById('binFilter').value='';loadTools()}
async function loadStats(){const d=await apiGet('/api/stats');document.getElementById('totalTools').textContent=d.total;document.getElementById('availableTools').textContent=d.available;document.getElementById('soldTools').textContent=d.sold;document.getElementById('totalValue').textContent='$'+d.available_value.toFixed(2);document.getElementById('totalRevenue').textContent='$'+d.revenue.toFixed(2);document.getElementById('withPhotos').textContent=d.with_photos}
async function loadLocations(){const d=await apiGet('/api/locations');const u=(id,items,label)=>{const s=document.getElementById(id);const cv=s.value;s.innerHTML=`<option value="">All ${label}</option>`+items.map(i=>`<option value="${i}">${i}</option>`).join('');s.value=cv};u('shelfFilter',d.shelves,'Shelves');u('rowFilter',d.rows,'Rows');u('binFilter',d.bins,'Bins')}
async function viewTool(id){const d=await apiGet('/api/tools');const t=d.tools.find(x=>x.id===id);if(!t)return;const loc=[t.shelf,t.row_num,t.bin].filter(Boolean).join(' / ')||'Not assigned';document.getElementById('modalContent').innerHTML=`<h2>${t.title}</h2><div style="margin:20px 0">${t.photo_url?`<img src="${t.photo_url}" style="max-width:100%;border-radius:12px;margin-bottom:15px">`:''}<div class="tool-price" style="font-size:1.6em">$${parseFloat(t.price).toFixed(2)}</div><p style="color:var(--g);margin:10px 0">${t.description||'No description'}</p><div class="tool-meta" style="margin:15px 0"><span>Condition: ${t.condition}</span><span>Location: ${loc}</span><span>Status: ${t.status}</span></div>${t.notes?`<p style="background:var(--l);padding:12px;border-radius:8px;margin:10px 0;font-size:.9em"><strong>Notes:</strong> ${t.notes}</p>`:''}<p style="color:var(--g);font-size:.85em">Barcode: ${t.barcode}</p><p style="color:var(--g);font-size:.85em">Added: ${new Date(t.created_at).toLocaleDateString()}</p>${t.status==='sold'?`<div style="background:#e8f5e9;padding:12px;border-radius:8px;margin-top:10px"><strong>Sold to:</strong> ${t.buyer_name||'N/A'}<br><strong>Sale Price:</strong> $${parseFloat(t.sale_price||0).toFixed(2)}<br><strong>Sale Date:</strong> ${t.sale_date?new Date(t.sale_date).toLocaleDateString():'N/A'}</div>`:''}</div><div class="barcode-container"><svg id="modalBarcode"></svg></div><div style="margin-top:20px;display:flex;gap:10px"><button class="btn btn-primary" onclick="printSingleLabel(${t.id});closeModal()">🖨️ Print Label</button><button class="btn btn-secondary" onclick="closeModal()">Close</button></div>`;document.getElementById('toolModal').classList.add('active');setTimeout(()=>{if(typeof JsBarcode!=='undefined')JsBarcode('#modalBarcode',t.barcode,{format:"CODE128",width:2,height:80,displayValue:true,fontSize:16})},100)}
async function editTool(id){const d=await apiGet('/api/tools');const t=d.tools.find(x=>x.id===id);if(!t)return;editingToolId=id;document.getElementById('toolTitle').value=t.title;document.getElementById('toolPrice').value=t.price;document.getElementById('toolDesc').value=t.description||'';document.getElementById('toolCondition').value=t.condition;document.getElementById('toolShelf').value=t.shelf||'';document.getElementById('toolRow').value=t.row_num||'';document.getElementById('toolBin').value=t.bin||'';document.getElementById('toolNotes').value=t.notes||'';document.getElementById('barcodeId').value=t.barcode;if(t.photo_url){document.getElementById('photoPreview').src=t.photo_url;document.getElementById('photoUpload').classList.add('has-image');document.getElementById('clearPhotoBtn').style.display='inline-block';currentPhoto=null;photoAction='keep'}else{currentPhoto=null;photoAction='none'}generateBarcodePreview(t.barcode);document.querySelector('#panel-add .card-title').textContent='✏️ Edit Tool';document.querySelector('button[type="submit"]').textContent='💾 Update Tool';switchTab('add')}
async function sellTool(id){const d=await apiGet('/api/tools');const t=d.tools.find(x=>x.id===id);if(!t)return;const buyer=prompt('Buyer name:');if(buyer===null)return;const sp=prompt('Sale price:',t.price);if(sp===null)return;await apiPost('/api/sell',{tool_id:id,buyer_name:buyer,sale_price:parseFloat(sp)});showToast('💰 Sold "'+t.title+'" to '+buyer+'!');loadTools();loadStats();loadAuditLog()}
async function deleteTool(id){if(!confirm('Delete this tool? Cannot be undone.'))return;await apiDelete('/api/tools/'+id);showToast('Tool deleted');loadTools();loadStats();loadLocations();loadAuditLog()}
function closeModal(){document.getElementById('toolModal').classList.remove('active')}
function toggleScanner(){const b=document.getElementById('cameraBtn');if(!scannerActive){if(typeof Quagga==='undefined'){showToast('Scanner library not loaded');return}Quagga.init({inputStream:{name:"Live",type:"LiveStream",target:document.getElementById('scanner-video'),constraints:{facingMode:"environment",width:{min:640},height:{min:480}}},decoder:{readers:["code_128_reader","ean_reader","ean_8_reader","code_39_reader"]},locator:{patchSize:"medium",halfSample:true}},err=>{if(err){showToast('Camera error: '+err.message);return}Quagga.start();scannerActive=true;b.textContent='⏹️ Stop Camera';showToast('Camera started')});Quagga.onDetected(r=>{handleScanResult(r.codeResult.code);toggleScanner()})}else{Quagga.stop();scannerActive=false;b.textContent='📷 Start Camera'}}
async function manualScan(){const c=document.getElementById('manualBarcode').value.trim();if(c){await handleScanResult(c);document.getElementById('manualBarcode').value=''}else showToast('Enter a barcode number')}
async function handleScanResult(code){code = String(code||'').trim();const d=await apiGet('/api/tools');const t=d.tools.find(x=>String(x.barcode||'').trim()===code);const r=document.getElementById('scanResult');if(t){const loc=[t.shelf,t.row_num,t.bin].filter(Boolean).join(' / ')||'Not assigned';r.className='scan-result found';r.innerHTML=`<h3>${t.title}</h3><p>${t.description||'No description'}</p><div class="tool-price">$${parseFloat(t.price).toFixed(2)}</div><div style="margin:10px 0;color:var(--g)"><strong>Location:</strong> ${loc}<br><strong>Condition:</strong> ${t.condition}<br><strong>Status:</strong> ${t.status}</div>${t.photo_url?`<img src="${t.photo_url}" style="max-width:250px;border-radius:12px;margin-top:10px">`:''}`;showToast('Found: '+t.title)}else{r.className='scan-result not-found';r.innerHTML='<h3>Tool Not Found</h3><p>No tool with barcode: <strong>'+code+'</strong></p><p>This barcode is not in your inventory.</p>';showToast('Tool not found')}}
async function updateLabelList(){const d=await apiGet('/api/tools',{status:'available'});const c=document.getElementById('labelList');if(d.tools.length===0){c.innerHTML='<p style="color:var(--g);text-align:center;padding:40px">No available tools.</p>';return}c.innerHTML=d.tools.map(t=>`<div class="label-item" onclick="toggleLabelSelection(this,${t.id})" data-id="${t.id}"><input type="checkbox" onchange="event.stopPropagation()"><div style="flex:1"><div style="font-weight:700">${t.title}</div><div style="color:var(--p);font-weight:700">$${parseFloat(t.price).toFixed(2)}</div><div style="font-size:.8em;color:var(--g)">${t.barcode} ${t.shelf?'| Shelf '+t.shelf:''} ${t.row_num?'Row '+t.row_num:''} ${t.bin?'Bin '+t.bin:''}</div></div></div>`).join('')}
function toggleLabelSelection(el,id){const cb=el.querySelector('input');cb.checked=!cb.checked;el.classList.toggle('selected',cb.checked)}
function selectAllLabels(){document.querySelectorAll('.label-item').forEach(el=>{el.querySelector('input').checked=true;el.classList.add('selected')})}
function deselectAllLabels(){document.querySelectorAll('.label-item').forEach(el=>{el.querySelector('input').checked=false;el.classList.remove('selected')})}
async function printSelectedLabels(){const sel=Array.from(document.querySelectorAll('.label-item.selected')).map(el=>parseInt(el.dataset.id));if(sel.length===0){showToast('Select at least one tool');return}const d=await apiGet('/api/tools');const tp=d.tools.filter(t=>sel.includes(t.id));printLabels(tp)}
async function printSingleLabel(id){const d=await apiGet('/api/tools');const t=d.tools.find(x=>x.id===id);if(t)printLabels([t])}
function printLabels(tools){const c=document.getElementById('printLabelContainer');c.innerHTML=tools.map(t=>{const loc=[t.shelf,t.row_num,t.bin].filter(Boolean).join('-');return`<div style="page-break-after:always;width:2in;padding:.1in;text-align:center;font-family:Arial,sans-serif"><div style="font-size:10pt;font-weight:bold;margin-bottom:4px;word-wrap:break-word">${t.title}</div><div style="font-size:13pt;font-weight:bold;color:#000;margin-bottom:4px">$${parseFloat(t.price).toFixed(2)}</div>${loc?`<div style="font-size:8pt;color:#666;margin-bottom:4px">${loc}</div>`:''}<svg id="print-barcode-${t.id}" style="max-width:1.8in;height:.5in"></svg></div>`}).join('');tools.forEach(t=>{if(typeof JsBarcode!=='undefined')JsBarcode('#print-barcode-'+t.id,t.barcode,{format:"CODE128",width:1.5,height:40,displayValue:true,fontSize:8,margin:0})});setTimeout(()=>window.print(),500)}
async function loadAuditLog(){const d=await apiGet('/api/audit',{limit:50});const c=document.getElementById('auditLog');if(d.logs.length===0){c.innerHTML='<p style="color:var(--g);text-align:center;padding:40px">No activity yet.</p>';return}c.innerHTML=d.logs.map(l=>`<div class="audit-entry"><div><div style="font-weight:600">${l.tool_title||'Deleted Tool'}</div><div style="font-size:.85em;color:var(--g)">${l.details}</div></div><div style="text-align:right"><span class="audit-action ${l.action}">${l.action}</span><div class="audit-time">${new Date(l.timestamp).toLocaleString()}</div></div></div>`).join('')}
async function exportCSV(){const d=await apiGet('/api/export');if(d.error){showToast(d.error);return}const blob=new Blob([d.csv],{type:'text/csv'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=d.filename;a.click();URL.revokeObjectURL(url);showToast('Exported '+d.count+' tools to CSV!')}
async function importCSV(e){const f=e.target.files[0];if(!f)return;const text=await f.text();const lines=text.split('\n').filter(l=>l.trim());const headers=lines[0].split(',').map(h=>h.trim().replace(/"/g,''));const items=[];for(let i=1;i<lines.length;i++){const values=lines[i].split(',').map(v=>v.trim().replace(/"/g,''));const item={};headers.forEach((h,idx)=>{item[h.toLowerCase()]=values[idx]||''});if(item.title)items.push(item)}if(items.length===0){showToast('No valid items found');return}if(!confirm('Import '+items.length+' tools?'))return;const r=await apiPost('/api/import',{items:items});showToast('Imported '+r.imported+' tools!');loadTools();loadStats();loadLocations();loadAuditLog()}
function showToast(m){const t=document.getElementById('toast');t.textContent=m;t.style.display='block';setTimeout(()=>t.style.display='none',3000)}
